Properly handle situation when /boot/vmlinuz is not here.

diff --git a/debian/boot-local-kernel.init b/debian/boot-local-kernel.init
--- a/debian/boot-local-kernel.init
+++ b/debian/boot-local-kernel.init
@@ -4,12 +4,20 @@
 
 case "$1" in
     start)
+        echo -n "Rebooting into local kernel: "
         case `uname -r` in
             *-nfsroot)
-                kexec -l /boot/vmlinuz
-                kexec -e
-                exit 1
-                ;;
+                if [ -e /boot/vmlinuz ]; then
+                    kexec -l /boot/vmlinuz
+                    echo "/boot/vmlinuz."
+                    kexec -e
+                    exit 1
+                else
+                    echo "failed, /boot/vmlinuz is missing."
+                    exit 1
+                fi;;
+            *)
+                echo "skipped, not a nfsroot.";;
         esac
         ;;
     stop|restart|force-reload)
